function makeRecord(partial) {
  const now = Date.now();
  return {
    id: crypto.randomUUID(),
    title: "",
    subtitle: "",
    creator: "",
    contributors: "",
    format: "Book",
    edition: "",
    year: "",
    publisher: "",
    identifier: "",
    genre: "",
    genres: [],
    binding: "",
    seriesName: "",
    seriesNumber: "",
    source: "",
    pricePaid: "",
    subjects: "",
    description: "",
    notes: "",
    location: "",
    callNumber: "",
    accessionNumber: `ACC-${Math.floor(Math.random() * 90000 + 10000)}`,
    status: "Available",
    dateAcquired: "",
    dateAdded: new Date(now).toISOString().slice(0, 10),
    addedAt: now,
    coverUrl: "",
    ...partial,
  };
}

export const sampleRecords = [
  makeRecord({
    title: "The Hobbit",
    creator: "J.R.R. Tolkien",
    format: "Book",
    year: 1937,
    publisher: "George Allen & Unwin",
    identifier: "9780261103344",
    genre: "Fantasy",
    genres: ["Fantasy"],
    binding: "Hardcover",
    subjects: "Fantasy, Adventure, Middle-earth",
    description: "Bilbo Baggins is drawn into a quest with dwarves and a wizard to reclaim a treasure hoard.",
    location: "Living Room Shelf A",
    callNumber: "FIC TOL",
    coverUrl: "https://images-na.ssl-images-amazon.com/images/I/81t2CVWEsUL.jpg",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
  }),
  makeRecord({
    title: "Kind of Blue",
    creator: "Miles Davis",
    contributors: "John Coltrane, Bill Evans",
    format: "Vinyl",
    year: 1959,
    publisher: "Columbia Records",
    identifier: "CL 1355",
    genre: "Jazz",
    genres: ["Jazz"],
    subjects: "Modal jazz, Trumpet, 1950s",
    description: "Landmark jazz recording featuring improvisational modal structures.",
    location: "Media Cabinet 2",
    callNumber: "VIN JAZ DAV",
    status: "Checked In",
    coverUrl: "https://upload.wikimedia.org/wikipedia/en/9/9c/MilesDavisKindofBlue.jpg",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  }),
  makeRecord({
    title: "Catan",
    creator: "Klaus Teuber",
    format: "Board Game",
    year: 1995,
    publisher: "Kosmos",
    identifier: "BGA-CATAN-BASE",
    genre: "Strategy",
    genres: ["Strategy"],
    subjects: "Resource management, Family games",
    description: "A classic board game about settling the island of Catan.",
    location: "Game Closet",
    callNumber: "GAME STR CAT",
    coverUrl: "https://upload.wikimedia.org/wikipedia/en/b/b0/Catan-2015-boxart.jpg",
    addedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  }),
  makeRecord({
    title: "A Brief History of Time",
    creator: "Stephen Hawking",
    format: "Book",
    year: 1988,
    publisher: "Bantam Dell",
    genre: "Nonfiction",
    genres: ["Nonfiction"],
    binding: "Paperback",
    subjects: "Cosmology, Physics, Science",
    location: "Office Shelf B",
    callNumber: "523.1 HAW",
    status: "On Loan",
  }),
  makeRecord({
    title: "Blue Train",
    creator: "John Coltrane",
    format: "Vinyl",
    year: 1957,
    publisher: "Blue Note",
    genre: "Jazz",
    genres: ["Jazz"],
    subjects: "Hard bop, Saxophone",
    location: "Media Cabinet 1",
    callNumber: "VIN JAZ COL",
  }),
];
